In [ ]:
## Import Statements & project setup
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import f1_score, roc_auc_score, accuracy_score
from sklearn.linear_model import LogisticRegression

from tensorflow.python.client import device_lib

In [ ]:
## Load data files
na_stats = pd.read_csv('/content/drive/MyDrive/ICS 637/NA_result.csv')
display(na_stats.head())
eu_stats = pd.read_csv('/content/drive/MyDrive/ICS 637/EU_result.csv')
display(eu_stats.head())

champIds = pd.read_csv('/content/drive/MyDrive/ICS 637/championIds.csv')
display(champIds.head())

matchId        blue1     blue2       blue3   blue4   blue5  \
0  NA1_4619747330         Gnar   Hecarim       Yasuo   Kaisa  Velkoz   
1  NA1_4619747324    Seraphine  Tristana       Teemo    Jinx    Jhin   
2  NA1_4619747323     Malphite      Udyr    Katarina  Twitch    Pyke   
3  NA1_4619747321        Neeko    LeeSin       Talon  KogMaw   Yuumi   
4  NA1_4619747318  Mordekaiser        Vi  Tryndamere   Sivir  Renata   

         red1      red2    red3      red4      red5  blueWin  
0      Illaoi  Nocturne    Ekko  Tristana       Lux        0  
1      Ezreal     Nasus    Ryze   Alistar     Galio        1  
2  Tryndamere  MasterYi  Akshan      Jinx     Yuumi        0  
3       Riven   Kindred  Qiyana     Nilah  Malphite        0  
4      Darius  Volibear  Rumble    Ezreal    Thresh        0

matchId        blue1    blue2        blue3   blue4     blue5  \
0  EUW1_6349620651         Ekko   Twitch          Lux  Illaoi  MasterYi   
1  EUW1_6349620650         Sion  Shyvana        Sylas   Sivir     Yuumi   
2  EUW1_6349620649        Riven  Warwick        Sylas   Nilah     Yuumi   
3  EUW1_6349620646  MissFortune    Quinn     Tristana   Corki    Ezreal   
4  EUW1_6349620645    Seraphine   Ezreal  AurelionSol  LeeSin     Riven   

     red1         red2         red3     red4        red5  blueWin  
0    Sett  MissFortune      Warwick     Ahri   Seraphine        1  
1   Teemo        Viego  TwistedFate  Kalista  Blitzcrank        1  
2      Vi        Amumu      Caitlyn     Jinx   Seraphine        1  
3  Ezreal        Nasus         Ryze  Alistar       Galio        1  
4   Jayce     Katarina         Nami      Zac       Nilah        0

champId    champName
0        1        Annie
1        2         Olaf
2        3        Galio
3        4  TwistedFate
4        5      XinZhao

In [ ]:
## Charts!
import matplotlib.pyplot as plt

plt.figure()
# eu_stats.blue1.value_counts()[:20].plot(kind='bar')
temp = eu_stats.blue1.value_counts()
champs = temp.index
nums = temp.values

for i in range(len(champs)):
  print(champs[i], nums[i])


Malphite 3653
Mordekaiser 3319
Sion 3064
Darius 2881
Jax 2870
Teemo 2800
Garen 2750
Sett 2730
Illaoi 2280
Chogath 2191
Nasus 2026
DrMundo 1921
Olaf 1828
Shen 1760
Fiora 1745
Quinn 1711
Yorick 1696
Riven 1456
Kayle 1421
Yone 1407
Caitlyn 1400
Gangplank 1386
Irelia 1360
Ornn 1340
Twitch 1301
Gwen 1291
Urgot 1268
MissFortune 1257
Kled 1256
Corki 1241
Camille 1234
Aatrox 1213
Akshan 1210
Pantheon 1140
Tryndamere 1138
Renekton 1114
Yasuo 1111
Jayce 1064
Gnar 1039
Warwick 1034
KSante 994
TahmKench 902
Gragas 808
Singed 804
Tristana 740
Volibear 737
Kennen 711
Vayne 707
Jinx 689
Akali 583
Sylas 344
MonkeyKing 334
Lux 321
Poppy 315
Rumble 306
Heimerdinger 293
Vladimir 290
Ashe 288
Lillia 277
Rengar 271
MasterYi 260
Rammus 259
Zed 253
Katarina 251
JarvanIV 243
Shaco 242
AurelionSol 238
Sejuani 236
Thresh 235
Senna 231
Udyr 229
LeeSin 226
Maokai 223
Kayn 217
Trundle 215
Graves 203
Veigar 190
Milio 186
Kaisa 182
Brand 180
Ezreal 180
Shyvana 173
Karma 171
Zac 162
Vi 161
Sivir 159
Malzahar 157
Dian

<Figure size 640x480 with 0 Axes>

In [ ]:
## Build champId dictionary
dictionary = dict()
for row in range(len(champIds)):
  dictionary[champIds.loc[row][0]] = champIds.loc[row][1]

for value in dictionary:
  print(dictionary.get(value))

Annie
Olaf
Galio
TwistedFate
XinZhao
Urgot
Leblanc
Vladimir
Fiddlesticks
Kayle
MasterYi
Alistar
Ryze
Sion
Sivir
Soraka
Teemo
Tristana
Warwick
Nunu
MissFortune
Ashe
Tryndamere
Jax
Morgana
Zilean
Singed
Evelynn
Twitch
Karthus
Chogath
Amumu
Rammus
Anivia
Shaco
DrMundo
Sona
Kassadin
Irelia
Janna
Gangplank
Corki
Karma
Taric
Veigar
Trundle
Swain
Caitlyn
Blitzcrank
Malphite
Katarina
Nocturne
Maokai
Renekton
JarvanIV
Elise
Orianna
MonkeyKing
Brand
LeeSin
Vayne
Rumble
Cassiopeia
Skarner
Heimerdinger
Nasus
Nidalee
Udyr
Poppy
Gragas
Pantheon
Ezreal
Mordekaiser
Yorick
Akali
Kennen
Garen
Leona
Malzahar
Talon
Riven
KogMaw
Shen
Lux
Xerath
Shyvana
Ahri
Graves
Fizz
Volibear
Rengar
Varus
Nautilus
Viktor
Sejuani
Fiora
Ziggs
Lulu
Draven
Hecarim
Khazix
Darius
Jayce
Lissandra
Diana
Quinn
Syndra
AurelionSol
Kayn
Zoe
Zyra
Kaisa
Seraphine
Gnar
Zac
Yasuo
Velkoz
Taliyah
Camille
Akshan
Belveth
Braum
Jhin
Kindred
Zeri
Jinx
TahmKench
Viego
Senna
Lucian
Zed
Kled
Ekko
Qiyana
Vi
Aatrox
Nami
Azir
Yuumi
Samira
Thresh
Il

In [ ]:
# ## Change champIds to champNames
# df = eu_stats.copy()
# df['blue1'] = df['blue1'].map(dictionary)
# df['blue2'] = df['blue2'].map(dictionary)
# df['blue3'] = df['blue3'].map(dictionary)
# df['blue4'] = df['blue4'].map(dictionary)
# df['blue5'] = df['blue5'].map(dictionary)

# df['red1'] = df['red1'].map(dictionary)
# df['red2'] = df['red2'].map(dictionary)
# df['red3'] = df['red3'].map(dictionary)
# df['red4'] = df['red4'].map(dictionary)
# df['red5'] = df['red5'].map(dictionary)

# display(df)
# df.to_csv('/content/drive/MyDrive/ICS 637/NA_result_modified.csv')

In [ ]:
## Create X and y variables for na_stats
X1 = na_stats[na_stats.columns[1:11]]
print(len(X1))

y1 = na_stats['blueWin'].tolist()
print(len(y1))

81676
81676


In [ ]:
## Create X and y variables for eu_stats
X2 = eu_stats[eu_stats.columns[1:11]]
print(len(X2))

y2 = eu_stats['blueWin'].tolist()
print(len(y2))

92105
92105


In [ ]:
## Combined inputs list
inputs = []

## Convert X1 to one-hot encoding
blue1_onehot = pd.get_dummies(X1.blue1).values
blue2_onehot = pd.get_dummies(X1.blue2).values
blue3_onehot = pd.get_dummies(X1.blue3).values
blue4_onehot = pd.get_dummies(X1.blue4).values
blue5_onehot = pd.get_dummies(X1.blue5).values

red1_onehot = pd.get_dummies(X1.red1).values
red2_onehot = pd.get_dummies(X1.red2).values
red3_onehot = pd.get_dummies(X1.red3).values
red4_onehot = pd.get_dummies(X1.red4).values
red5_onehot = pd.get_dummies(X1.red5).values


for i in range(len(blue1_onehot)):
  index = []
  index.append(blue1_onehot[i])
  index.append(blue2_onehot[i])
  index.append(blue3_onehot[i])
  index.append(blue4_onehot[i])
  index.append(blue5_onehot[i])
  index.append(red1_onehot[i])
  index.append(red2_onehot[i])
  index.append(red3_onehot[i])
  index.append(red4_onehot[i])
  index.append(red5_onehot[i])
  index = np.asarray(index)
  index = index.flatten()
  inputs.append(index)

In [ ]:
## Convert X2 to one-hot encoding
blue1_onehot = pd.get_dummies(X2.blue1).values
blue2_onehot = pd.get_dummies(X2.blue2).values
blue3_onehot = pd.get_dummies(X2.blue3).values
blue4_onehot = pd.get_dummies(X2.blue4).values
blue5_onehot = pd.get_dummies(X2.blue5).values

red1_onehot = pd.get_dummies(X2.red1).values
red2_onehot = pd.get_dummies(X2.red2).values
red3_onehot = pd.get_dummies(X2.red3).values
red4_onehot = pd.get_dummies(X2.red4).values
red5_onehot = pd.get_dummies(X2.red5).values


for i in range(len(blue1_onehot)):
  index = []
  index.append(blue1_onehot[i])
  index.append(blue2_onehot[i])
  index.append(blue3_onehot[i])
  index.append(blue4_onehot[i])
  index.append(blue5_onehot[i])
  index.append(red1_onehot[i])
  index.append(red2_onehot[i])
  index.append(red3_onehot[i])
  index.append(red4_onehot[i])
  index.append(red5_onehot[i])
  index = np.asarray(index)
  index = index.flatten()
  inputs.append(index)

In [ ]:
## Build dictionary for one hot encoding champion String
test = pd.get_dummies(X2.red5)
champions = test.columns.values
onehot_dict = dict()
for i in range(len(champions)):
  encoding = np.zeros((163), dtype=int)
  encoding[i] = 1
  onehot_dict[champions[i]] = encoding

In [ ]:
## Combine y lists
y = np.concatenate((y1, y2))
print(len(y))

## Convert inputs to numpy array
inputs = np.asarray(inputs)
print(inputs.shape)

173781
(173781, 1630)


In [ ]:
# Build training and testing datasets
X_train, X_test, y_train, y_test = train_test_split(inputs, y, test_size=0.2, random_state=42)

In [ ]:
print(X_train.shape)

(139024, 1630)


In [ ]:
# Create Neural Network
model = MLPClassifier(alpha=1e-4, hidden_layer_sizes=(20, 20, 20, 10, 5), random_state=1, max_iter=300)
# model = LogisticRegression(random_state=1) # Alternate model for result comparison

# Fit the model to our training data
model.fit(X_train, y_train)

# Get predictions
y_pred = model.predict(X_test)

In [ ]:
## Get scores from model

# Get f1 score
f1score = f1_score(y_test, y_pred, average='macro')
accuracy = accuracy_score(y_test, y_pred)

In [ ]:
## Display results
print('F1 Score: ', f1score)
print('Accuracy: ', accuracy)

F1 Score:  0.6670925725673542
Accuracy:  0.6728428805708203


In [ ]:
## Get a prediction!!

## Fill in team compositions
blueTeam = ['Teemo', 'Lux', 'Lux', 'Lux', 'Lux']
redTeam = ['Lux', 'Lux', 'Lux', 'Lux', 'Lux']

## Convert to onehot
for i in range(len(blueTeam)):
  blueTeam[i] = onehot_dict[blueTeam[i]]
  redTeam[i] = onehot_dict[redTeam[i]]

input = np.concatenate((blueTeam, redTeam))
input = input.flatten()
print(input)

## Prediction
prediction = model.predict_proba([input])
print(prediction)




[0 0 0 ... 0 0 0]
[[0.44807392 0.55192608]]


In [ ]:
## What is the OPTIMAL team composition???
picks = []
for i in range(10):
  if i < 5:
    picks.append(onehot_dict['Teemo'])
  else:
    picks.append(onehot_dict['Lucian'])
picks = np.asarray(picks).flatten()

print(model.predict_proba([picks]))



  


[[9.99999853e-01 1.46857188e-07]]
